### ISSUE TITLE
eu-south-1 is an invalid AWS region

### ISSUE THREAD

**Issue by mkjsix** [karl-cardenas-coding/go-lambda-cleanup#36] opened 2022-08-07 21:23 UTC
**Describe the bug**

The region eu-south-1 is a valid AWS region (Europe - Milan), but the program labels it as invalid.

**To Reproduce**

Run the command like this:

`docker run -e AWS_ACCESS_KEY_ID=***** -e AWS_SECRET_ACCESS_KEY=****** ghcr.io/karl-cardenas-coding/go-lambda-cleanup:1.0.15 clean -r eu-south-1`

Result:

`time=08/07/22 level=fatal msg="eu-south-1 is an invalid AWS region. If this is an error please"`

**Expected behavior**

It should work as with any other AWS region.

**Desktop (please complete the following information):**

Docker version 20.10.17, build 100c701 on MacOS 12.5 (Intel)

**Comment by karl-cardenas-coding** [comment] 2022-08-07 21:51
Hi @mkjsix, thanks for reporting this bug. I'm gonna take a peek here shortly.

**Comment by karl-cardenas-coding** [comment] 2022-08-07 22:00
Looks like the issue is resolved by adding the flag `--all-regions` in the AWS CLI command used to generate the list
```shell
aws ec2 describe-regions --all-regions --region us-east-1 --query "Regions[].RegionName"
```

I'm gonna push the fix now.

**Comment by karl-cardenas-coding** [comment] 2022-08-07 22:08
@mkjsix version `1.0.16` contains the fix. Thanks again for reporting this.

**Closed** 2022-08-07 22:07 UTC

**Comment by mkjsix** [comment] 2022-08-08 08:52
Hi @karl-cardenas-coding 
I confirm the issue has been resolved, thank you.
